const items = [
  [
    {
      name: 'cry',
      translate: 'плакать',
      image: `/cards/action-a/cry.jpg`,
      audio: `/audio/action-a/cry.mp3`,
      id: 1,
    },
    {
      name: 'dance',
      translate: 'танцевать',
      image: `/cards/action-a/dance.jpg`,
      audio: `/audio/action-a/dance.mp3`,
      id: 2,
    },
    {
      name: 'dive',
      translate: 'нырять',
      image: `/cards/action-a/dive.jpg`,
      audio: `/audio/action-a/dive.mp3`,
      id: 3,
    },
    {
      name: 'draw',
      translate: 'рисовать',
      image: `/cards/action-a/draw.jpg`,
      audio: `/audio/action-a/draw.mp3`,
      id: 4,
    },
    {
      name: 'fish',
      translate: 'ловить рыбу',
      image: `/cards/action-a/fish.jpg`,
      audio: `/audio/action-a/fish.mp3`,
      id: 5,
    },
    {
      name: 'fly',
      translate: 'летать',
      image: `/cards/action-a/fly.jpg`,
      audio: `/audio/action-a/fly.mp3`,
      id: 6,
    },
    {
      name: 'hug',
      translate: 'обнимать',
      image: `/cards/action-a/hug.jpg`,
      audio: `/audio/action-a/hug.mp3`,
      id: 7,
    },
    {
      name: 'jump',
      translate: 'прыгать',
      image: `/cards/action-a/jump.jpg`,
      audio: `/audio/action-a/jump.mp3`,
      id: 8,
    },
  ],
  [
    {
      name: 'open',
      translate: 'открывать',
      image: `/cards/action-b/open.jpg`,
      audio: `/audio/action-b/open.mp3`,
      id: 1,
    },
    {
      name: 'play',
      translate: 'играть',
      image: `/cards/action-b/play.jpg`,
      audio: `/audio/action-b/play.mp3`,
      id: 2,
    },
    {
      name: 'point',
      translate: 'указывать',
      image: `/cards/action-b/point.jpg`,
      audio: `/audio/action-b/point.mp3`,
      id: 3,
    },
    {
      name: 'ride',
      translate: 'ездить',
      image: `/cards/action-b/ride.jpg`,
      audio: `/audio/action-b/ride.mp3`,
      id: 4,
    },
    {
      name: 'run',
      translate: 'бегать',
      image: `/cards/action-b/run.jpg`,
      audio: `/audio/action-b/run.mp3`,
      id: 5,
    },
    {
      name: 'sing',
      translate: 'петь',
      image: `/cards/action-b/sing.jpg`,
      audio: `/audio/action-b/sing.mp3`,
      id: 6,
    },
    {
      name: 'skip',
      translate: 'пропускать',
      image: `/cards/action-b/skip.jpg`,
      audio: `/audio/action-b/skip.mp3`,
      id: 7,
    },
    {
      name: 'swim',
      translate: 'плавать',
      image: `/cards/action-b/swim.jpg`,
      audio: `/audio/action-b/swim.mp3`,
      id: 8,
    },
  ],
  [
    {
      name: 'cat',
      translate: 'кошка',
      image: `/cards/animal-a/cat.jpg`,
      audio: `/audio/animal-a/cat.mp3`,
      id: 1,
    },
    {
      name: 'chick',
      translate: 'цыпленок',
      image: `/cards/animal-a/chick.jpg`,
      audio: `/audio/animal-a/chick.mp3`,
      id: 2,
    },
    {
      name: 'chicken',
      translate: 'курица',
      image: `/cards/animal-a/chicken.jpg`,
      audio: `/audio/animal-a/chicken.mp3`,
      id: 3,
    },
    {
      name: 'dog',
      translate: 'собака',
      image: `/cards/animal-a/dog.jpg`,
      audio: `/audio/animal-a/dog.mp3`,
      id: 4,
    },
    {
      name: 'horse',
      translate: 'лошадь',
      image: `/cards/animal-a/horse.jpg`,
      audio: `/audio/animal-a/horse.mp3`,
      id: 5,
    },
    {
      name: 'pig',
      translate: 'свинья',
      image: `/cards/animal-a/pig.jpg`,
      audio: `/audio/animal-a/pig.mp3`,
      id: 6,
    },
    {
      name: 'rabbit',
      translate: 'кролик',
      image: `/cards/animal-a/rabbit.jpg`,
      audio: `/audio/animal-a/rabbit.mp3`,
      id: 7,
    },
    {
      name: 'sheep',
      translate: 'овца',
      image: `/cards/animal-a/sheep.jpg`,
      audio: `/audio/animal-a/sheep.mp3`,
      id: 8,
    },
  ],
  [
    {
      name: 'bird',
      translate: 'птица',
      image: `/cards/animal-b/bird.jpg`,
      audio: `/audio/animal-b/bird.mp3`,
      id: 1,
    },
    {
      name: 'dolphin',
      translate: 'дельфин',
      image: `/cards/animal-b/dolphin.jpg`,
      audio: `/audio/animal-b/dolphin.mp3`,
      id: 2,
    },
    {
      name: 'fish',
      translate: 'рыба',
      image: `/cards/animal-b/fish.jpg`,
      audio: `/audio/animal-b/fish.mp3`,
      id: 3,
    },
    {
      name: 'frog',
      translate: 'лягушка',
      image: `/cards/animal-b/frog.jpg`,
      audio: `/audio/animal-b/frog.mp3`,
      id: 4,
    },
    {
      name: 'giraffe',
      translate: 'жираф',
      image: `/cards/animal-b/giraffe.jpg`,
      audio: `/audio/animal-b/giraffe.mp3`,
      id: 5,
    },
    {
      name: 'lion',
      translate: 'лев',
      image: `/cards/animal-b/lion.jpg`,
      audio: `/audio/animal-b/lion.mp3`,
      id: 6,
    },
    {
      name: 'mouse',
      translate: 'мышь',
      image: `/cards/animal-b/mouse.jpg`,
      audio: `/audio/animal-b/mouse.mp3`,
      id: 7,
    },
    {
      name: 'turtle',
      translate: 'черепаха',
      image: `/cards/animal-b/turtle.jpg`,
      audio: `/audio/animal-b/turtle.mp3`,
      id: 8,
    },
  ],
  [
    {
      name: 'blouse',
      translate: 'блузка',
      image: `/cards/clothes/blouse.jpg`,
      audio: `/audio/clothes/blouse.mp3`,
      id: 1,
    },
    {
      name: 'boot',
      translate: 'ботинок',
      image: `/cards/clothes/boot.jpg`,
      audio: `/audio/clothes/boot.mp3`,
      id: 2,
    },
    {
      name: 'coat',
      translate: 'пальто',
      image: `/cards/clothes/coat.jpg`,
      audio: `/audio/clothes/coat.mp3`,
      id: 3,
    },
    {
      name: 'dress',
      translate: 'платье',
      image: `/cards/clothes/dress.jpg`,
      audio: `/audio/clothes/dress.mp3`,
      id: 4,
    },
    {
      name: 'pants',
      translate: 'брюки',
      image: `/cards/clothes/pants.jpg`,
      audio: `/audio/clothes/pants.mp3`,
      id: 5,
    },
    {
      name: 'shirt',
      translate: 'футболка',
      image: `/cards/clothes/shirt.jpg`,
      audio: `/audio/clothes/shirt.mp3`,
      id: 6,
    },
    {
      name: 'shoe',
      translate: 'туфля',
      image: `/cards/clothes/shoe.jpg`,
      audio: `/audio/clothes/shoe.mp3`,
      id: 7,
    },
    {
      name: 'skirt',
      translate: 'юбка',
      image: `/cards/clothes/skirt.jpg`,
      audio: `/audio/clothes/skirt.mp3`,
      id: 8,
    },
  ],
  [
    {
      name: 'angry',
      translate: 'злой',
      image: `/cards/emotions/angry.jpg`,
      audio: `/audio/emotions/angry.mp3`,
      id: 1,
    },
    {
      name: 'happy',
      translate: 'счастливый',
      image: `/cards/emotions/happy.jpg`,
      audio: `/audio/emotions/happy.mp3`,
      id: 2,
    },
    {
      name: 'laugh',
      translate: 'смеющийся',
      image: `/cards/emotions/laugh.jpg`,
      audio: `/audio/emotions/laugh.mp3`,
      id: 3,
    },
    {
      name: 'sad',
      translate: 'грустный',
      image: `/cards/emotions/sad.jpg`,
      audio: `/audio/emotions/sad.mp3`,
      id: 4,
    },
    {
      name: 'scared',
      translate: 'испуганный',
      image: `/cards/emotions/scared.jpg`,
      audio: `/audio/emotions/scared.mp3`,
      id: 5,
    },
    {
      name: 'smile',
      translate: 'улыбающийся',
      image: `/cards/emotions/smile.jpg`,
      audio: `/audio/emotions/smile.mp3`,
      id: 6,
    },
    {
      name: 'surprised',
      translate: 'удивленный',
      image: `/cards/emotions/surprised.jpg`,
      audio: `/audio/emotions/surprised.mp3`,
      id: 7,
    },
    {
      name: 'tired',
      translate: 'уставший',
      image: `/cards/emotions/tired.jpg`,
      audio: `/audio/emotions/tired.mp3`,
      id: 8,
    },
  ],
  [
    {
      name: 'apple',
      translate: 'яблоко',
      image: `/cards/food/apple.jpg`,
      audio: `/audio/food/apple.mp3`,
      id: 1,
    },
    {
      name: 'cookie',
      translate: 'печенье',
      image: `/cards/food/cookie.jpg`,
      audio: `/audio/food/cookie.mp3`,
      id: 2,
    },
    {
      name: 'cucumber',
      translate: 'огурец',
      image: `/cards/food/cucumber.jpg`,
      audio: `/audio/food/cucumber.mp3`,
      id: 3,
    },
    {
      name: 'ham',
      translate: 'ветчина',
      image: `/cards/food/ham.jpg`,
      audio: `/audio/food/ham.mp3`,
      id: 4,
    },
    {
      name: 'meat',
      translate: 'мясо',
      image: `/cards/food/meat.jpg`,
      audio: `/audio/food/meat.mp3`,
      id: 5,
    },
    {
      name: 'milk',
      translate: 'молоко',
      image: `/cards/food/milk.jpg`,
      audio: `/audio/food/milk.mp3`,
      id: 6,
    },
    {
      name: 'potato',
      translate: 'картофель',
      image: `/cards/food/potato.jpg`,
      audio: `/audio/food/potato.mp3`,
      id: 7,
    },
    {
      name: 'sausage',
      translate: 'сосиска',
      image: `/cards/food/sausage.jpg`,
      audio: `/audio/food/sausage.mp3`,
      id: 8,
    },
  ],
  [
    {
      name: 'airport',
      translate: 'аэропорт',
      image: `/cards/travelling/airport.jpg`,
      audio: `/audio/travelling/airport.mp3`,
      id: 1,
    },
    {
      name: 'bus',
      translate: 'автобус',
      image: `/cards/travelling/bus.jpg`,
      audio: `/audio/travelling/bus.mp3`,
      id: 2,
    },
    {
      name: 'luggage',
      translate: 'багаж',
      image: `/cards/travelling/luggage.jpg`,
      audio: `/audio/travelling/luggage.mp3`,
      id: 3,
    },
    {
      name: 'passport',
      translate: 'паспорт',
      image: `/cards/travelling/passport.jpg`,
      audio: `/audio/travelling/passport.mp3`,
      id: 4,
    },
    {
      name: 'resort',
      translate: 'курорт',
      image: `/cards/travelling/resort.jpg`,
      audio: `/audio/travelling/resort.mp3`,
      id: 5,
    },
    {
      name: 'ticket',
      translate: 'билет',
      image: `/cards/travelling/ticket.jpg`,
      audio: `/audio/travelling/ticket.mp3`,
      id: 6,
    },
    {
      name: 'tourist',
      translate: 'турист',
      image: `/cards/travelling/tourist.jpg`,
      audio: `/audio/travelling/tourist.mp3`,
      id: 7,
    },
    {
      name: 'train',
      translate: 'поезд',
      image: `/cards/travelling/train.jpg`,
      audio: `/audio/travelling/train.mp3`,
      id: 8,
    },
  ],
];

export default items;
